#!/bin/bash

# Start wdb server
wdb.server.py &

# Debug from the begining
if [ "$1" == "start" ]; then
    export ODOO_SERVER="python -m wdb $(which $ODOO_SERVER)"
    launch

# Run unit tests with debugger enabled
elif [ "$1" == "unittest" ]; then
    unittest "$2"

# Just run the normal server with wdb started
else
    launch
fi
