#!/bin/bash

if [ -f /firstrun ]; then
    echo Patching configuration on first run

    echo "
[options]
; Configuration file generated by $(readlink --canonicalize $0)
addons_path = /usr/local/lib/python2.7/dist-packages/openerp/addons,/opt/odoo/extra-addons
unaccent = True
db_host = $DB_PORT_5432_TCP_ADDR
db_port = $DB_PORT_5432_TCP_PORT
db_user = $DB_ENV_POSTGRESQL_USER
db_password = $DB_ENV_POSTGRESQL_PASS
database = $DB_ENV_POSTGRESQL_DB
admin_passwd = $ADMIN_PASSWD" > /etc/openerp/openerp-server.conf

    rm /firstrun
fi

# Run server
su openerp --command "openerp-server --config /etc/openerp/openerp-server.conf"
