#!/bin/bash

odoo="openerp-gevent --config /etc/openerp/openerp-server.conf"

if [ -f /firstrun ]; then
    echo Patching configuration on first run

    echo "
[options]
; Configuration file generated by $(readlink --canonicalize $0)
addons_path = /usr/local/lib/python2.7/dist-packages/openerp/addons,/opt/odoo/extra-addons
unaccent = True
db_host = $DB_PORT_5432_TCP_ADDR
db_port = $DB_PORT_5432_TCP_PORT
db_user = $DB_ENV_POSTGRESQL_USER
db_password = $DB_ENV_POSTGRESQL_PASS
database = $DB_ENV_POSTGRESQL_DB
admin_passwd = $ADMIN_PASSWD" > /etc/openerp/openerp-server.conf

    rm /firstrun

    # Workaround of for web module not being installed
    # https://github.com/odoo/odoo/issues/953#issuecomment-54597695
    su openerp --command "$odoo --init base,web --database $DB_ENV_POSTGRESQL_DB"

else
    # Run server with live chat enabled
    su openerp --command "$odoo"
fi
