#!/bin/bash

# These variables are used in many scripts

home=/home/odoo

# Workaround when default settings are used in database container
# https://github.com/wyaeld/dockerfiles/issues/4
DB_ENV_POSTGRESQL_USER=${DB_ENV_POSTGRESQL_USER:-"docker"}
DB_ENV_POSTGRESQL_PASS=${DB_ENV_POSTGRESQL_PASS:-"docker"}
DB_ENV_POSTGRESQL_DB=${DB_ENV_POSTGRESQL_DB:-"docker"}
