FROM oondeo/odoo-deps:onbuild
MAINTAINER Juan Ramon Alfaro <info@oondeo.es>

ENV ODOO_MODULES="https://github.com/oondeo/git-install/archive/8.0.zip https://github.com/oondeo/odoo_apps/archive/8.0.zip https://github.com/OCA/l10n-spain/archive/8.0.zip https://github.com/OCA/web/archive/8.0.zip https://github.com/OCA/e-commerce/archive/8.0.zip https://github.com/OCA/sale-workflow/archive/8.0.zip https://github.com/OCA/product-attribute/archive/8.0.zip https://github.com/OCA/bank-statement-import/archive/8.0.zip https://github.com/OCA/hr-timesheet/archive/8.0.zip https://github.com/OCA/product-variant/archive/8.0.zip https://github.com/OCA/account-payment/archive/8.0.zip https://github.com/OCA/website/archive/8.0.zip https://github.com/OCA/knowledge/archive/8.0.zip https://github.com/OCA/project/archive/8.0.zip https://github.com/OCA/report-print-send/archive/8.0.zip https://github.com/OCA/commission/archive/8.0.zip"
ENV PYTHON_MODULES="$PYTHON_MODULES flanker odoo_gateway"

CMD ["launch"]
