#!/sh

export XZ_OPT="-9"
export BUILD_DIR=/tmp/wkhtmltopdf
export QMAKESPEC=$BUILD_DIR/qt/mkspecs/linux-g++-64
export QT_CONFIG="-opensource \
        -confirm-license \
        -fast \
        -release \
        -static \
        -graphicssystem raster \
        -webkit \
        -exceptions \
        -xmlpatterns \
        -system-zlib \
        -system-libpng \
        -system-libjpeg \
        -no-libmng \
        -no-libtiff \
        -no-accessibility \
        -no-stl \
        -no-qt3support \
        -no-phonon \
        -no-phonon-backend \
        -no-opengl \
        -no-declarative \
        -no-script \
        -no-scripttools \
        -no-sql-ibase \
        -no-sql-mysql \
        -no-sql-odbc \
        -no-sql-psql \
        -no-sql-sqlite \
        -no-sql-sqlite2 \
        -no-mmx \
        -no-3dnow \
        -no-sse \
        -no-sse2 \
        -no-multimedia \
        -nomake demos \
        -nomake docs \
        -nomake examples \
        -nomake tools \
        -nomake tests \
        -nomake translations
        -silent \
        -xrender \
        -largefile \
        -iconv \
        -openssl \
        -no-javascript-jit \
        -no-rpath \
        -no-dbus \
        -no-nis \
        -no-cups \
        -no-pch \
        -no-gtkstyle \
        -no-nas-sound \
        -no-sm \
        -no-xshape \
        -no-xinerama \
        -no-xcursor \
        -no-xfixes \
        -no-xrandr \
        -no-mitshm \
        -no-xinput \
        -no-xkb \
        -no-glib \
        -no-gstreamer \
        -no-icu \
        -no-openvg \
        -no-xsync \
        -no-audio-backend \
        -no-sse3 \
        -no-ssse3 \
        -no-sse4.1 \
        -no-sse4.2 \
        -no-avx \
        -no-neon"


set -e


cd /tmp

git clone --recursive --branch $WKHTMLTOX_VERSION --depth 1 https://github.com/wkhtmltopdf/wkhtmltopdf.git
curl -o aports-$ALPINE_VERSION.tbz2 http://git.alpinelinux.org/cgit/aports/snapshot/aports-$ALPINE_VERSION.tar.bz2
tar -jxf  aports-$ALPINE_VERSION.tbz2
#curl -O -sL http://download.qt.io/official_releases/qt/5.6/5.6.0/single/qt-everywhere-opensource-src-$QT_VERSION.tar.gz
#tar -zxf  qt-everywhere-opensource-src-$QT_VERSION.tar.gz
#mv  qt-everywhere-opensource-src-$QT_VERSION/* wkhtmltopdf/qt/
mkdir -p $BUILD_DIR/linux-generic-amd64/qt
mkdir -p $BUILD_DIR/linux-generic-amd64/app/bin
mkdir -p $BUILD_DIR/linux-generic-amd64/dist
cd $BUILD_DIR/qt
for source in /tmp/aports-$ALPINE_VERSION/main/qt/*.patch
do
  patch -p1 -i $source
done
cd $BUILD_DIR/qt
../qt/configure $QT_CONFIG --prefix=$BUILD_DIR/linux-generic-amd64/qt
make -j$(getconf _NPROCESSORS_ONLN)
make install
cp -a include $BUILD_DIR/linux-generic-amd64/qt
cd $BUILD_DIR/linux-generic-amd64/app
../qt/bin/qmake $BUILD_DIR/wkhtmltopdf.pro
make -j$(getconf _NPROCESSORS_ONLN)
cp bin/wkhtmlto* /usr/bin/
cp -P bin/lib* /usr/lib/
install-deps bin/*

rm -rf /tmp/*
