#!/sh

#get running dependencies for compiled programs
runDeps="$( \
  		scanelf --needed --nobanner --recursive "$@" \
  			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
  			| sort -u \
  			| xargs -r apk info --installed \
  			| sort -u \
  	)"

apk add --no-cache --virtual .rundeps $runDeps
