#!/sh

apt-get update && apt-get install -y --no-install-recommends $BUILD_PACKAGES
paxctl -Cm /usr/bin/nodejs
paxctl -Cm /usr/bin/ruby
$PIP_BIN --no-cache-dir install $PYTHON_MODULES
cd /usr/lib/python2.7/site-packages && python -m compileall .
rm -rf /var/lib/apt/* /var/tmp/* /tmp/* /var/log/* ~/.cache || true
