#!/bin/bash

# This program patches the configuration for Odoo and then runs the server

# Set some running config options
#set XDG_DATA_HOME for module install
#export XDG_DATA_HOME=/var/lib/odoo/Odoo/addons/$ODOO_VERSION

#set -e

function download () {
    url=$1
    branch="$ODOO_VERSION"
    rm -rf /tmp/module
    mkdir -p /tmp/module
    cd /tmp/module
    echo "Downloading $url"
    #git repo download with git
    IFS=':' read -ra ADDR <<< "$url"
    repo="${ADDR[0]}:${ADDR[1]}"
    if [[ "${repo:0:3}" == "git" || "${repo:0:3}" == "ssh" || "${repo:${#repo}-3:${#repo}}" == "git" ]]
    then
        echo "GIT: ${ADDR[*]}"
        if [ "${#ADDR[@]}" == "3" ];then
            branch="${ADDR[2]}"
            git clone --depth 1 -b $branch "$repo" || true
        else
            git clone --depth 1 "$repo" || true
        fi
        mv "$(ls -1d *)" "$(ls -1d *)-$branch"
    else
        echo "Download using curl"
        curl --location -o module.zip "$url" && unzip -q ./module.zip -d . && rm module.zip
    fi
    #instalamos las dependencias de los modulos
    ADDON=$(ls -1d *)
    if [ ! -d $ODOO_ADDONS_HOME/$ADDON ]; then
        mv $ADDON $ODOO_ADDONS_HOME/
    fi
}

function install () {
    ADDON=$1
    ODOO_ADDONS_HOME=$2
    echo "Instalando $ADDON"
    if [ "0" == "$(ls -1 $ODOO_ADDONS_HOME/$ADDON/*/$ODOO_MODULE_FILE | wc -l)" ]; then
        echo "Procesando $ADDON"

        if [ -f $ODOO_ADDONS_HOME/$ADDON/oca_dependencies.txt ]; then
            sed -i '/^[[:blank:]]*#/d;s/#.*//' $ODOO_ADDONS_HOME/$ADDON/oca_dependencies.txt
            sed -i '/^$/d' $ODOO_ADDONS_HOME/$ADDON/oca_dependencies.txt
            while read -u 10 rawline; do
                IFS=' ' read -ra ARRLINE <<< "$rawline"
                if [ "${#ARRLINE[@]}" == "1" ]; then
                    line="${OCA_URL}/${rawline}.git:$branch"
                else
                    if  [ ${#ARRLINE[@]} -gt 2 ]; then
                        branch="${ARRLINE[2]}"
                    fi
                    repo=${ARRLINE[1]}
                    if [[ "${repo:0:3}" == "git" || "${repo:0:3}" == "ssh" || "${repo:${#repo}-3:${#repo}}" == "git" ]]; then
                        line="${ARRLINE[1]}:$branch"
                    else
                        line="${ARRLINE[1]}.git:$branch"
                    fi
                fi
                if [ ! -d $ODOO_ADDONS_HOME/${ARRLINE[0]}-$ODOO_VERSION ]; then
                    download $line
                    install ${ARRLINE[0]}-$ODOO_VERSION $ODOO_ADDONS_HOME
                fi
            done 10<$ODOO_ADDONS_HOME/$ADDON/oca_dependencies.txt

        fi
        if [ -f $ODOO_ADDONS_HOME/$ADDON/requirements.txt ]; then
            $PIP_BIN install --no-cache-dir -r $ODOO_ADDONS_HOME/$ADDON/requirements.txt || true
        fi
        cd $ODOO_ADDONS_HOME/$ADDON && $PYTHON_BIN -m compileall .
    fi
}

cd /tmp
if [ ! -f $ODOO_HOME/addons/web/__init__.pyc ]; then
    if [ ! -f $ODOO_HOME/addons/web/__init__.py ]; then
        curl --location --remote-name "$ODOO_URL" && \
        unzip -q ./$ODOO_VERSION.zip -d ./ && \
        cp -aP $ODOO_TARBALL_DIR/* $ODOO_HOME && rm -rf $ODOO_TARBALL_DIR
    fi
    $PIP_BIN install --no-cache-dir -r $ODOO_HOME/requirements.txt || exit 1
    cd $ODOO_HOME || exit 1
    $PYTHON_BIN setup.py develop && make || exit 1
    $PYTHON_BIN  -m compileall . || exit 1
fi
#OLDIFS=$IFS
#IFS=$'\n'
for url in $ODOO_MODULES
do
    download "$url"
done

for elem in $ODOO_ADDONS_HOME/*
do
    install "$(basename $elem)" $ODOO_ADDONS_HOME
done

for elem in "$1"/*
do
    install "$(basename $elem)" "$1"
done

cd $PYTHON_DIR/site-packages && python -m compileall .
cd "$ODOO_ADDONS_HOME"
find -type d -name ".git" -exec rm -rf {} \;
rm -rf ~/.cache /tmp/*
